# Generated by Django 5.1.2 on 2025-01-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio_details',
        ),
    ]
